language: ruby
rvm:
  - 2.1
install: bundle install 
script: jekyll build
gemfile:
  - content/Gemfile
notifications:
  slack: 
    rooms:
      -   noltarium:slacktoken#publicbuilds
    on_success: always
  