sitedata:
  image: busybox
  volumes:
    - .:/src

htmlcontent:
  image: busybox
  volumes:
    - /usr/share/nginx/html 

jekyll: 
  build: .
  working_dir: /src/content
  environment:
    - JEKYLL_DESTINATION=/usr/share/nginx/html/jekyll-site
    - JEKYLL_WATCH=true
  volumes_from:
    - sitedata
    - htmlcontent
  command: "build"  
  
  
web:
  image: nginx
  volumes_from:
    - htmlcontent
  ports:
    - 80:80  