sitedata:
  image: busybox
  volumes:
    - ./content:/src

htmlcontent:
  image: busybox
  volumes:
    - /usr/share/nginx/html 

jekyll: 
  build: .
  environment:
    - JEKYLL_DESTINATION=/usr/share/nginx/html
  volumes_from:
    - sitedata
    - htmlcontent
  command: "build"  
  
  
web:
  image: nginx
  volumes_from:
    - htmlcontent
  ports:
    - 80:80  