# name of the software
name: Web Card
# current version of the software
version: 1.1.0

baseurl: /jekyll-site

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

emptyArray: []          