# name of the software
name: Web Card
# current version of the software
version: 1.1.0

ditaa_output_directory: /assets/images/ditaa
# ditaa_debug_mode: true

keen_api_readKey: 2c8b72bf508f6343758403cc99066b7bdc30aa6ae89a70873e263e33981d3b4e750140761d5a1600c49b752b4fc119c051c72ee036d4b770b7ae1a4f203829934cfc50b9066b752ec4d2871039e59252e147e9876e1a6ae86fc8111766988662
keen_projectId: 578d609a80a7bd79bfd6cb0a

baseurl: /jekyll-site
category_dir: blog/categories

collections:
  posts:
    output:   true
  electronic:
    output:   true   

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /blog/:year/:month/:day/:title/
timezone: UTC

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-time-to-read
  
paginate: 5          # Posts per page on the blog index
paginate_path: "blog/posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"  

disqus_short_name: nolte-jekyll-site

emptyArray: []          
