# name of the software
name: Home Stuff Documentation
# current version of the software
version: 1.1.0
# url of the download button
#downloadUrl: https://github.com/mistic100/jekyll-bootstrap-doc
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/nolte

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/nolte

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: nolte
  repo: 

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap


collections:
  docker_applications:
    output: true
    permalink: /container/application/:path/
    defaults:
      - scope:
          path: ""
          type: docker_applications
        values:
          layout: docker-application
  docker_images:
    output: true
    permalink: /container/images/:path/
    defaults:
      - scope:
          path: ""
          type: docker_images
        values:
          layout: docker-image 
  projects:
    output: true
    permalink: /project/:path/
    defaults:
      - scope:
          path: ""
          type: project
        values:
          layout: project         
          