source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-mentions'
gem 'jemoji'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'github-pages', group: :jekyll_plugins
gem 'activesupport', '< 5.0'
gem 'business' 
gem 'html-proofer'
